### ISSUE TITLE
Get tests running in Docker

### ISSUE THREAD

**Issue by adolski** [medusa-project/book-tracker#23]
I can't remember if you had Docker experience already, @gaurijo, but if not, one way to learn about it is through the [Docker documentation](https://docs.docker.com). You also have access to [LinkedIn Learning](http://go.illinois.edu/linkedinlearning) courses through the U of I, and it looks like they have quite a few on Docker.

The basic idea is, instead of running `rails test` from our shell, we want to spin up the Book Tracker in a container and run `rails test` in that. Alongside the Book Tracker container we will need another container for PostgreSQL, so we will want to use docker compose to orchestrate these multiple containers.

The Book Tracker is already containerized for running in AWS ECS. But the image is built for running the web app and not the tests. It would be possible to use the same image for both, but, in other projects, the way I've set it up is with separate images, generated by separate Dockerfiles.

An example of another app that is setup with separate web app & test containers, and works in ECS and GitHub Actions, is [metaslurp](https://github.com/medusa-project/metaslurp). In this project there is a root-level Dockerfile (for the web app) and a separate test Dockerfile in `docker/metaslurp-test/Dockerfile`. The docker-compose.yml file is used for testing, and it spins up three separate containers, one for the main app and two for its dependent services.

One thing I'm not sure about yet is how to build an x86 container image from an ARM Mac, but I think that's a solvable problem once we get to it.

**Comment by gaurijo** [comment]
I dabbled with Docker for a project several months ago but didn't experience setting it up myself, so I'll definitely take a look at the resources you linked. Thanks!

**Comment by gaurijo** [comment]
@adolski I have made some decent progress (i think), with a docker image built for the tests but am figuring out the best way to utilize Docker Compose to run everything at once. Right now in my `docker-compose.yml file,` I have two services (book-tracker and postgres db), but I'm not sure if I need to split this up into three services (book-tracker app, book-tracker tests, and postgres db?) or if the way I have it set up covers both the web app and the tests:

```
version: '3'

services:
  postgres: 
    hostname: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: book_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 

  book-tracker:
    build: 
      context: . 
      dockerfile: docker/book-tracker-test/Dockerfile
    environment:
      RAILS_ENV: test
    ports: 
      - "3000:3000"
    depends_on:
      - postgres 
```
### Some notes/questions:

1. I chose `postgres:14-alpine` based on seeing that I have `postgres v 14 `running, but unsure if that's relevant
2. Inside the book-tracker service, I'm calling on the tests, confirming what port the db should be exposed to, and added a `depends_on` so that the book-tracker service knows to wait for postgres connection; `do I also need to include any commands here?`
3. When I check `docker ps` I get the following output: 
```
CONTAINER ID   IMAGE                COMMAND                  CREATED          STATUS          PORTS      NAMES
a8655e516656   postgres:14-alpine   "docker-entrypoint.s…"   12 minutes ago   Up 12 minutes   5432/tcp   book-tracker-postgres-1
```
4. However when I run `docker-compose up` I get several errors about` port 5432` that I'm confused by
```
could not connect to server: Connection refused (ActiveRecord::ConnectionNotEstablished)
book-tracker-book-tracker-1  |  Is the server running on host "localhost" (127.0.0.1) and accepting
book-tracker-book-tracker-1  |  TCP/IP connections on port 5432?
```

I'll continue reading through the docs/watching docker videos, but wanted to see if you might notice anything here that's an immediate red flag.

**Comment by adolski** [comment]
The way I've dealt with this in other projects is to break out the development and test versions of the app into separate docker-compose files. (We don't really even need a development one for Book Tracker.) For example, in [this project](https://github.com/medusa-project/ideals), there are three different compose files:

1. `docker-compose.yml` contains all of the services that both versions of the app depend on, but not the app itself
2. `docker-compose.development.yml` contains only the development version of the app
3. `docker-compose.test.yml` contains only the test version of the app

Then `docker compose` can be invoked like:

`docker compose -f docker-compose.yml -f docker-compose.test.yml up --build --exit-code-from ideals-test`

----

Postgres 14 should be fine, unless any errors turn up, but I doubt they will.

And the project link above, and the `docker-compose.test.yml` file within it should answer the other questions. (I should have linked to it before, sorry.)

**Comment by gaurijo** [comment]
@adolski Thank you! I'll see how it goes splitting it up like this. 

Should I follow the structure of how it's set up in Ideals, where all Dockerfiles are nested inside the docker directory? The way book-tracker is currently set up, has one Dockerfile living in the same directory as the project root.

**Comment by adolski** [comment]
I think it's better to put them in a subdirectory, because it reduces clutter in the root directory, and moreso if you ever have to add more of them (for other services).

**Comment by gaurijo** [comment]
Update: 

1. I reinstalled the latest version of Docker Desktop and it's running (for now!)
2. Still running into issues with Docker Compose:

I set up a subdirectory for the dockerfiles: `/docker/book-tracker-app/Dockerfile `and `/docker/book-tracker-test/Dockerfile`

Here's how I set up the test Dockerfile:
```
FROM ruby:3.0.3-slim 

ENV RAILS_ENV=test
ENV RAILS_LOG_TO_STDOUT=true 
ENV RAILS_MAX_THREADS=5
ENV RAILS_SERVE_STATIC_FILES=true 

RUN apt-get update && apt-get install -y \
  build-essential \
  curl \
  git \
  libpq-dev 

RUN mkdir app 
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler \ 
    && bundle config set without 'development' \
    && bundle install 

COPY . ./

CMD ["bin/rails", "test"]
```

Here is my docker-compose.yml:

```
version: '3'

services:
  postgres: 
    hostname: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: book_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"

  book-tracker:
    build: 
      context: . 
      dockerfile: docker/book-tracker-app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres 
```

Here is the docker-compose.test.yml:

```
version: '3'

services:
  book-tracker-test:
    build:
      context: .
      dockerfile: docker/book-tracker-test/Dockerfile 
    depends_on:
      - postgres
    command: bash -c "sleep 40 && bin/rails db:prepare & bin/rails test"
```

I also updated my config/database.yml to include 'host:postgres' in the default config block:

```
default: &default
  adapter:  postgresql
  encoding: unicode
  host: postgres 
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000
  min_messages: warning
  template: template0
```

Finally, upon running `docker compose -f docker-compose.yml -f docker-compose.test.yml up` here's the output I'm getting (I'm running into an error with the postgres username and password not being authenticated, which I'm having trouble figuring out why)




![Image](https://github.com/medusa-project/book-tracker/assets/103534307/97b22392-3f30-4c9f-b27b-3ec0960217d1)



![Image](https://github.com/medusa-project/book-tracker/assets/103534307/b312528d-65e2-4f09-bb66-cda647a4d2a4)



![Image](https://github.com/medusa-project/book-tracker/assets/103534307/2b898561-63a9-49f2-945a-2d19c6c7303b)
