### ISSUE TITLE
Switch from omniauth-shibboleth to omniauth-saml

### ISSUE THREAD

**Issue by adolski** [medusa-project/book-tracker#30]
Blocks #27

**Comment by adolski** [comment]
This is working in demo. Will work on production next.

**Comment by adolski** [comment]
@gaurijo In order to get this working, I've had to add some more configuration keys, which you'll need to add to your `config/development.yml` and `test.yml` files. I think you can just leave them blank:

```yaml
hostname:
saml:
  sp_entity_id:
  sp_private_key:
  idp_sso_service_url:
  idp_sso_service_binding:
```
